version: '3'

services:
  nginx:
    image: nginx:1.15.5-alpine
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - ./extra/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./extra/docker/nginx/logs/:/var/log/nginx/
    ports:
      - 80
    depends_on:
      - php

  php:
    build: extra/docker/php/fpm
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    depends_on:
      - mariadb
      - redis

  php_worker:
    build: extra/docker/php/cli
    restart: always
    working_dir: /app
    command: ["php", "artisan", "queue:work", "--sleep=1", "--tries=3"]
    volumes:
      - ./:/app/
    depends_on:
      - php

  mariadb:
    image: mariadb:10.2.14
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306
    volumes:
      - ./extra/docker/mariadb:/var/lib/mysql

  redis:
    image: redis:5.0-alpine3.8
    restart: always
    ports:
      - 6379

  mail:
    image: miladrahimi/fake-smtp
    restart: always
    working_dir: /output
    volumes:
      - ./storage/mails:/output
    ports:
      - 25
