version: '3'

services:
  nginx:
    container_name: shaftaloo_nginx
    image: nginx:1.15.5-alpine
    restart: always
    working_dir: /app/
    volumes:
    - ./:/app/
    - ./extra/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./extra/docker/nginx/logs/:/var/log/nginx/
    ports:
    - ${APP_PORT}:80
    environment:
    - NGINX_HOST=localhost
    depends_on:
    - php

  php:
    container_name: shaftaloo_php
    image: miladrahimi/php:7.2-fpm-alpine3.8
    restart: always
    working_dir: /app/
    volumes:
    - ./:/app/
    depends_on:
    - mariadb

  mariadb:
    container_name: shaftaloo_mariadb
    image: mariadb:10.2.18
    restart: always
    environment:
    - MYSQL_DATABASE=${DB_DATABASE}
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
    - ${DB_EXPOSED_PORT}:3306
    volumes:
    - ./extra/docker/mariadb/data:/var/lib/mysql
