version: '3'

services:
  nginx:
    container_name: shaftaloo_nginx
    image: nginx:1.15.5-alpine
    volumes:
    - ./:/app/
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./docker/nginx/logs/:/var/log/nginx/
    ports:
    - 80
    environment:
    - NGINX_HOST=localhost
    working_dir: /app/
    restart: always
    depends_on:
    - php

  php:
    container_name: shaftaloo_php
    image: miladrahimi/php:7.2-fpm-alpine3.8
    restart: always
    volumes:
    - ./:/app/
    - ./docker/php/php.ini-${APP_ENV:-testing}:/usr/local/etc/php/php.ini
    working_dir: /app/
    depends_on:
    - mysql

  mysql:
    container_name: shaftaloo_mysql
    image: mysql:5.7.24
    environment:
    - MYSQL_DATABASE=${DB_DATABASE:-app}
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
    restart: always
    ports:
    - 3306
    volumes:
    - ./docker/mariadb/data:/var/lib/mysql
