---
- hosts: defaults
  gather_facts: false
  become: true
  remote_user: root
  tasks:
    - name: Pull the last verion of project from Github
      git:
        repo: "https://github.com/miladrahimi/shaftaloo"
        dest: "{{ remote_dir }}"

    - name: Create .env if not exists
      copy:
        src: "{{ remote_dir }}/.env.example"
        dest: "{{ remote_dir }}/.env"
        remote_src: yes
        force: no

    - name: Down the current instance of the app
      docker_service:
        project_src: "{{ remote_dir }}"
