---
- hosts: all
  gather_facts: false
  become: true
  remote_user: root
  tasks:
    - name: Pull the last verion of project from Github
      git:
        repo: "https://github.com/miladrahimi/shaftaloo"
        dest: "{{ remote_dir | default('/var/www/shaftaloo') }}"

    - name: Create .env if not exists
      copy:
        src: "{{ remote_dir | default('/var/www/shaftaloo') }}/.env.example"
        dest: "{{ remote_dir | default('/var/www/shaftaloo') }}/.env"
        remote_src: yes
        force: no

    - name: Change storage permission
      command: chmod -R 0777 {{ remote_dir | default('/var/apps/shaftaloo') }}/storage

    - name: Change cache permission
      command: chmod -R 0777 {{ remote_dir | default('/var/apps/shaftaloo') }}/bootstrap/cache

    - name: Run the app via docker-compose
      command: chdir={{ remote_dir | default('/var/apps/shaftaloo') }} docker-compose up -d

    - name: Wait for database
      command: >
        docker exec shaftaloo_mariadb
        mysqladmin ping -uroot -p{{ db_password|secret }}
      register: result
      until: not result.rc
      retries: 20
      delay: 3

    - name: Install the Composer depencencies
      command: docker exec shaftaloo_php composer install

    - name: Down the app
      command: "docker exec shaftaloo_php php artisan down"

    - name: Run migrations
      command: "docker exec shaftaloo_php php artisan migrate"

    - name: Up the app
      command: "docker exec shaftaloo_php php artisan up"
